### ISSUE TITLE
Unexpected Infinity::indet, Min::meprec, and Max::meprec issued from UnivariateMTPDecisionV2`DecideMTP?

### ISSUE THREAD

**Issue by PoeticExposition** [xiaxueqaq/MTP-decision#1] opened 2023-08-09 09:17 UTC
Here is a short example: 
```Mathematica
In[1]:= <<"…/MTP-decision-main/UnivariateMTPDecisionV2.wl"(*file path*)

In[2]:= Block[{Print},EchoTiming[DecideMTP[{c1,c2}\[VectorGreater]0\[Implies]c3\[LessEqual]0,{c1,c2,c3},{\[Pi]-x,\[Pi]+x,(1+2*Cos[x])/3-(9-2*x^2)/(9+2*x*Tan[x/2])},x,!False],Method\[Rule]Timing]]

>> 3.8125

Out[2]= True

In[3]:= Block[{Print},EchoTiming[DecideMTP[Inequality[\[Pi],Greater,x,Greater,-\[Pi]]\[Implies]c3\[LessEqual]0,{c3},{(1+2*Cos[x])*(9+2*x*Tan[x/2])-3*(9-2*x^2)},x,!False],Method\[Rule]Timing]]

>> 2.5625

Out[3]= True

In[4]:= Block[{Print},EchoTiming[DecideMTP[{c1,c2}\[VectorGreater]0\[Implies]c3\[LessEqual]0,{c1,c2,c3},{\[Pi]-x,\[Pi]+x,(1+2*Cos[x])*(9+2*x*Tan[x/2])-3*(9-2*x^2)},x,!False],Method\[Rule]Timing]]

Infinity::indet: Indeterminate expression 0 Pi ComplexInfinity encountered.

>> 2.5625

Out[4]= True
```
These statements are the same in essence, but why does `In[4]` produce a message underneath the input? 
Edit. Here is another instance: 
```Mathematica
In[5]:= Block[{Print},EchoTiming[DecideMTP[x\[Element]NonNegativeReals\[Implies]c0\[NotElement]NonNegativeReals,{c0},{TrigExpand[(4*x^2-3*\[Pi]^2)*Sin[2*x]+2*x*(\[Pi]^2*Cos[2*x]+2*(\[Pi]^2-2*x^2))]},x],Method\[Rule]Timing]]

Min::meprec: Internal precision limit $MaxExtraPrecision = 50. reached while evaluating 
      1                            4         2        4    2                  2    4          6
    -(-) (Sqrt[3] Pi) - Root[{-9 Pi  + (96 Pi  + 48 Pi ) #1  + (-256 - 1024 Pi ) #1  + 4096 #1  & , -1.360349523175663}].
      4

Min::meprec: Internal precision limit $MaxExtraPrecision = 50. reached while evaluating 
      1                            4         2        4    2                  2    4          6
    -(-) (Sqrt[3] Pi) - Root[{-9 Pi  + (96 Pi  + 48 Pi ) #1  + (-256 - 1024 Pi ) #1  + 4096 #1  & , -1.360349523175663}].
      4

Max::meprec: Internal precision limit $MaxExtraPrecision = 50. reached while evaluating 
      1                            4         2        4    2                  2    4          6
    -(-) (Sqrt[3] Pi) + Root[{-9 Pi  + (96 Pi  + 48 Pi ) #1  + (-256 - 1024 Pi ) #1  + 4096 #1  & , 1.360349523175663}].
      4

Max::meprec: Internal precision limit $MaxExtraPrecision = 50. reached while evaluating 
      1                            4         2        4    2                  2    4          6
    -(-) (Sqrt[3] Pi) + Root[{-9 Pi  + (96 Pi  + 48 Pi ) #1  + (-256 - 1024 Pi ) #1  + 4096 #1  & , 1.360349523175663}].
      4

>> 3.0625

Out[5]= True

In[6]:= Block[{Print},EchoTiming[DecideMTP[x\[Element]NonNegativeReals\[Implies]c0\[NotElement]NonNegativeReals,{c0},{TrigFactor[(4*x^2-3*\[Pi]^2)*Sin[2*x]+2*x*(\[Pi]^2*Cos[2*x]+2*(\[Pi]^2-2*x^2))]},x],Method\[Rule]Timing]]

>> 4.40625

Out[6]= True

In[7]:= Block[{Print},EchoTiming[DecideMTP[x\[Element]NonNegativeReals\[Implies]c0\[NotElement]NonNegativeReals,{c0},{TrigReduce[(4*x^2-3*\[Pi]^2)*Sin[2*x]+2*x*(\[Pi]^2*Cos[2*x]+2*(\[Pi]^2-2*x^2))]},x],Method\[Rule]Timing]]

>> 0.234375

Out[7]= True
```
Actually, these three results are all incorrect. But why does ``UnivariateMTPDecisionV2`DecideMTP`` simply return `True`?

**Comment by xiaxueqaq** [comment] 2023-08-09 11:32
> Here is a short example:
> 
> ```mathematica
> In[1]:= <<"…/MTP-decision-main/UnivariateMTPDecisionV2.wl"(*file path*)
> 
> In[2]:= Block[{Print},EchoTiming[DecideMTP[{c1,c2}\[VectorGreater]0\[Implies]c3\[LessEqual]0,{c1,c2,c3},{\[Pi]-x,\[Pi]+x,(1+2*Cos[x])/3-(9-2*x^2)/(9+2*x*Tan[x/2])},x,!False],Method\[Rule]Timing]]
> 
> >> 3.8125
> 
> Out[2]= True
> 
> In[3]:= Block[{Print},EchoTiming[DecideMTP[Inequality[\[Pi],Greater,x,Greater,-\[Pi]]\[Implies]c3\[LessEqual]0,{c3},{(1+2*Cos[x])*(9+2*x*Tan[x/2])-3*(9-2*x^2)},x,!False],Method\[Rule]Timing]]
> 
> >> 2.5625
> 
> Out[3]= True
> 
> In[4]:= Block[{Print},EchoTiming[DecideMTP[{c1,c2}\[VectorGreater]0\[Implies]c3\[LessEqual]0,{c1,c2,c3},{\[Pi]-x,\[Pi]+x,(1+2*Cos[x])*(9+2*x*Tan[x/2])-3*(9-2*x^2)},x,!False],Method\[Rule]Timing]]
> 
> Infinity::indet: Indeterminate expression 0 Pi ComplexInfinity encountered.
> 
> >> 2.5625
> 
> Out[4]= True
> ```
> 
> These statements are the same in essence, but why does `In[4]` produce a message underneath the input? Edit. Here is another instance:
> 
> ```mathematica
> In[5]:= Block[{Print},EchoTiming[DecideMTP[x\[Element]NonNegativeReals\[Implies]c0\[NotElement]NonNegativeReals,{c0},{TrigExpand[(4*x^2-3*\[Pi]^2)*Sin[2*x]+2*x*(\[Pi]^2*Cos[2*x]+2*(\[Pi]^2-2*x^2))]},x],Method\[Rule]Timing]]
> 
> Min::meprec: Internal precision limit $MaxExtraPrecision = 50. reached while evaluating 
>       1                            4         2        4    2                  2    4          6
>     -(-) (Sqrt[3] Pi) - Root[{-9 Pi  + (96 Pi  + 48 Pi ) #1  + (-256 - 1024 Pi ) #1  + 4096 #1  & , -1.360349523175663}].
>       4
> 
> Min::meprec: Internal precision limit $MaxExtraPrecision = 50. reached while evaluating 
>       1                            4         2        4    2                  2    4          6
>     -(-) (Sqrt[3] Pi) - Root[{-9 Pi  + (96 Pi  + 48 Pi ) #1  + (-256 - 1024 Pi ) #1  + 4096 #1  & , -1.360349523175663}].
>       4
> 
> Max::meprec: Internal precision limit $MaxExtraPrecision = 50. reached while evaluating 
>       1                            4         2        4    2                  2    4          6
>     -(-) (Sqrt[3] Pi) + Root[{-9 Pi  + (96 Pi  + 48 Pi ) #1  + (-256 - 1024 Pi ) #1  + 4096 #1  & , 1.360349523175663}].
>       4
> 
> Max::meprec: Internal precision limit $MaxExtraPrecision = 50. reached while evaluating 
>       1                            4         2        4    2                  2    4          6
>     -(-) (Sqrt[3] Pi) + Root[{-9 Pi  + (96 Pi  + 48 Pi ) #1  + (-256 - 1024 Pi ) #1  + 4096 #1  & , 1.360349523175663}].
>       4
> 
> >> 3.0625
> 
> Out[5]= True
> 
> In[6]:= Block[{Print},EchoTiming[DecideMTP[x\[Element]NonNegativeReals\[Implies]c0\[NotElement]NonNegativeReals,{c0},{TrigFactor[(4*x^2-3*\[Pi]^2)*Sin[2*x]+2*x*(\[Pi]^2*Cos[2*x]+2*(\[Pi]^2-2*x^2))]},x],Method\[Rule]Timing]]
> 
> >> 4.40625
> 
> Out[6]= True
> 
> In[7]:= Block[{Print},EchoTiming[DecideMTP[x\[Element]NonNegativeReals\[Implies]c0\[NotElement]NonNegativeReals,{c0},{TrigReduce[(4*x^2-3*\[Pi]^2)*Sin[2*x]+2*x*(\[Pi]^2*Cos[2*x]+2*(\[Pi]^2-2*x^2))]},x],Method\[Rule]Timing]]
> 
> >> 0.234375
> 
> Out[7]= True
> ```
> 
> Actually, these three results are all incorrect. But why does `` UnivariateMTPDecisionV2`DecideMTP `` simply return `True`?

First, thanks a lot for your interests in our project! Could you please provide what version of Mathematica you are using, because I cannot reproduce the issue in my PC.

But possibly I can explain why there are error messages. In our paper [(ISSAC' 23, Chen and Xia)](https://dl.acm.org/doi/abs/10.1145/3597066.3597104), we restrict the topic on **rational** univariate mixed trigonometric-polynomials, i.e., all the coefficients are rational numbers. The reason for this is twofold: 1. we need to carry the computation over a computable field (Q, or its algebraic closure) because a Turing machine actually cannot store a real number. 2. there is a problem recognizing zero (i.e. deciding an expression is 0 or not), which can be solved in Q or its algebraic closure, by Lindemann-Weierstrass Theorem. The MTPs in your example contains Pi, which is transcendental and is actually beyond the ability of our algorithm.

However, there is a workaround to your first example: instead of saying -Pi<x<Pi, we can use $$((\sin x>0) \wedge (x>0) \wedge (x<4)) \vee ((\sin x<0) \wedge (x<0) \wedge (x>-4)) \vee (x=0)$$ to specify this domain, the code is: 
```mathematica
> In[1]:= DecideMTP[(((b1 > 0) \[And] (b2 > 0) \[And] (b3 < 0)) \[Or] ((b1 < 
        0) \[And] (b2 < 0) \[And] (b3 > 0)) \[Or] (b2 = 
      0)) \[Implies] (b5 <= 0), {b1, b2, b3, b4, b5}, {Sin[x], x, 
  x - 4, x + 4, (1 + 2*Cos[x])*(9 + 2*x*Tan[x/2]) - 3*(9 - 2*x^2)}, x]
> Out[1]= True
```

By the way, I know this input is somewhat peculiar (the first input is a quantifier-free propositional formula, the second is the set of placeholders for MTP, and the third is the MTPs...), this is mainly because I was in a hurry submitting the paper and had no time to write a parser for extracting MTPs from a first-order formula in MTPs. When I am not so busy, I will try to make the input  more clear to users.

Thanks again for your interest, if you have any problem, please feel free to reply or contact me by email, which is in the paper!

**Comment by PoeticExposition** [comment] 2023-08-09 15:26
> First, thanks a lot for your interests in our project! Could you please provide what version of Mathematica you are using, because I cannot reproduce the issue in my PC.
> 
Thanks for your reply. The `$Version` is `13.3.0 for Microsoft Windows (64-bit) (June 3, 2023)` (which is the latest release at present).
The examples above are considered quite sharp (e.g,, ${\left(1+2\cos{x}\right)}{\left(9+2x\tan\dfrac{x}2\right)}-3{\left(9-2x^2\right)}\sim-\dfrac1{840}x^8,~x\to0$), but now I find a much simple instance (_not_ containing $π$): ![iExample1](https://github.com/xiaxueqaq/MTP-decision/assets/118050799/be801e36-d2ba-401b-b4f3-c12fc580436e)
It appears that there exists some bug in the implementation. May you confirm this? (Incidentally, it is **alleged** that it is inadvisable to use the explicit ``For`` in Mathematica in general.)

**Comment by xiaxueqaq** [comment] 2023-08-09 15:46
> 



> > First, thanks a lot for your interests in our project! Could you please provide what version of Mathematica you are using, because I cannot reproduce the issue in my PC.
> 
> Thanks for your reply. The `$Version` is `13.3.0 for Microsoft Windows (64-bit) (June 3, 2023)` (which is the latest release at present). The examples above are considered quite sharp (e.g,, (1+2cos⁡x)(9+2xtan⁡x2)−3(9−2x2)∼−1840x8, x→0), but now I find a much simple instance (_not_ containing π): ![iExample1](https://github.com/xiaxueqaq/MTP-decision/assets/118050799/be801e36-d2ba-401b-b4f3-c12fc580436e) It appears that there exists some bug in the implementation. May you confirm this? (Incidentally, it is **alleged** that it is inadvisable to use the explicit `For` in Mathematica in general.)



> > First, thanks a lot for your interests in our project! Could you please provide what version of Mathematica you are using, because I cannot reproduce the issue in my PC.
> 
> Thanks for your reply. The `$Version` is `13.3.0 for Microsoft Windows (64-bit) (June 3, 2023)` (which is the latest release at present). The examples above are considered quite sharp (e.g,, (1+2cos⁡x)(9+2xtan⁡x2)−3(9−2x2)∼−1840x8, x→0), but now I find a much simple instance (_not_ containing π): ![iExample1](https://github.com/xiaxueqaq/MTP-decision/assets/118050799/be801e36-d2ba-401b-b4f3-c12fc580436e) It appears that there exists some bug in the implementation. May you confirm this? (Incidentally, it is **alleged** that it is inadvisable to use the explicit `For` in Mathematica in general.)

Dear PoeticExposition: 

The definition of univariate mixed trigonometric-polynomial with rational coefficients excludes expressions like $\sin x/x$ (Definition 2.9 in our paper), because it would be a rational function in $x,\sin x,\cos x$ instead of a polynomial in them. If you really want to do this with our package, I suggest multiplying an even power of the denominator and use $f \ne 0$ to exclude the zero of the denominators. In your example, the following code works:

```mathematica
DecideMTP[(f1 < 0) \[Implies] (f2 < 0), {f1, f2}, {x, Sin[x] x - x^2},  x]
```

**Comment by xiaxueqaq** [comment] 2023-08-09 15:56
> > First, thanks a lot for your interests in our project! Could you please provide what version of Mathematica you are using, because I cannot reproduce the issue in my PC.
> 
> Thanks for your reply. The `$Version` is `13.3.0 for Microsoft Windows (64-bit) (June 3, 2023)` (which is the latest release at present). The examples above are considered quite sharp (e.g,, (1+2cos⁡x)(9+2xtan⁡x2)−3(9−2x2)∼−1840x8, x→0), but now I find a much simple instance (_not_ containing π): ![iExample1](https://github.com/xiaxueqaq/MTP-decision/assets/118050799/be801e36-d2ba-401b-b4f3-c12fc580436e) It appears that there exists some bug in the implementation. May you confirm this? (Incidentally, it is **alleged** that it is inadvisable to use the explicit `For` in Mathematica in general.)

Yes, I agree that one should not mix procedural programming with functional programming, especially in Mathematica, which is  fully functional. Well, the thing is, when the deadline of submission comes, it is better to have a (possibly bad) implementation than to have nothing at all. As you have read, I was really in a hurry writing a usable package and did the experiements, so the code is a direct translation from the pseudo-code in the paper. Of course it could be better, and I probably will rewrite it in the future. But you are encouraged to write a fully functional implementation!

**Comment by PoeticExposition** [comment] 2023-08-10 11:30
> The definition of univariate mixed trigonometric-polynomial with rational coefficients excludes expressions like sin⁡x/x (Definition 2.9 in our paper), because it would be a rational function in x,sin⁡x,cos⁡x instead of a polynomial in them. If you really want to do this with our package, I suggest multiplying an even power of the denominator and use f≠0 to exclude the zero of the denominators. In your example, the following code works:
> 

Thanks for your reminder. Now I read the definitions carefully. The program does not seem to automatically support either $\cos{2x},\sin{3x}$ or $\cot{x},\sec{x}$. Right? 
Besides, I find a strange behavior. Consider the following inequality (similar to the "Example 3"): $$x^{10}\sin^6x\geqslant243x\cos x{\left(\sin x-x\cos x\right)}^5,~\forall x\inℝ\textnormal{,}$$ (which is related to ${\left(\frac{\tan x}x\right)}^5\leqslant{\left(\frac{\tan x-x}{x^3/3}\right)}^5\leqslant{\left(\frac{\tan x}x\right)}^6$ for ${\left\lvert x\right\rvert}<\fracπ2$ (Surprisingly, ${\left(\frac{\tanh x}x\right)}^{10}\leqslant{\left(\frac{x-\tanh x}{x^3/3}\right)}^5\leqslant{\left(\frac{\tanh x}x\right)}^6$ holds as well.)). On my ***low-end*** computer, when I run 
```Mathematica
DecideMTP[b1 - b2 \[GreaterSlantEqual] 0, {b1, b2}, {x^10 * Sin[x] ^ 6, 243 * x * Cos[x]
     * (Sin[x] - x * Cos[x]) ^ 5}, x]
```
the elapsed time is 2.15625s, while if I use 
```Mathematica
DecideMTP[b0 \[GreaterSlantEqual] 0, {b0}, {x^10 * Sin[x] ^ 6 - 243 * x * Cos[x] * (Sin[
    x] - x * Cos[x]) ^ 5}, x]
```
the execution time will be 166.375s instead. (Moreover, though `TrigFactor[b0]` returns something like $\dotsm+\dotsm\sin{2x}+\dotsm\sin{4x}+\dotsm\sin{6x}+\dotsm\cos{2x}+\dotsm\cos{4x}+\dotsm\cos{6x}$, yet if I input the alternative version `b0/.x->x/2` (where `TrigReduce/*TrigExpand` has to be applied in advance), the evaluation will not finish even in a quarter of an hour!) What is the reason for it?

**Comment by xiaxueqaq** [comment] 2023-08-11 09:55
> > The definition of univariate mixed trigonometric-polynomial with rational coefficients excludes expressions like sin⁡x/x (Definition 2.9 in our paper), because it would be a rational function in x,sin⁡x,cos⁡x instead of a polynomial in them. If you really want to do this with our package, I suggest multiplying an even power of the denominator and use f≠0 to exclude the zero of the denominators. In your example, the following code works:
> 
> Thanks for your reminder. Now I read the definitions carefully. The program does not seem to automatically support either cos⁡2x,sin⁡3x or cot⁡x,sec⁡x. Right? Besides, I find a strange behavior. Consider the following inequality (similar to the "Example 3"): x10sin6⁡x⩾243xcos⁡x(sin⁡x−xcos⁡x)5, ∀x∈ℝ, (which is related to (tan⁡xx)5⩽(tan⁡x−xx3/3)5⩽(tan⁡xx)6 for |x|<π2 (Surprisingly, (tanh⁡xx)10⩽(x−tanh⁡xx3/3)5⩽(tanh⁡xx)6 holds as well.)). On my _**low-end**_ computer, when I run
> 
> ```mathematica
> DecideMTP[b1 - b2 \[GreaterSlantEqual] 0, {b1, b2}, {x^10 * Sin[x] ^ 6, 243 * x * Cos[x]
>      * (Sin[x] - x * Cos[x]) ^ 5}, x]
> ```
> 
> the elapsed time is 2.15625s, while if I use
> 
> ```mathematica
> DecideMTP[b0 \[GreaterSlantEqual] 0, {b0}, {x^10 * Sin[x] ^ 6 - 243 * x * Cos[x] * (Sin[
>     x] - x * Cos[x]) ^ 5}, x]
> ```
> 
> the execution time will be 166.375s instead. (Moreover, though `TrigFactor[b0]` returns something like ⋯+⋯sin⁡2x+⋯sin⁡4x+⋯sin⁡6x+⋯cos⁡2x+⋯cos⁡4x+⋯cos⁡6x, yet if I input the alternative version `b0/.x->x/2` (where `TrigReduce/*TrigExpand` has to be applied in advance), the evaluation will not finish even in a quarter of an hour!) What is the reason for it?

1. Yes, our package does no preprocessing, so the users have to handle the expression to match the input format;
2. Actually the output of your first call is unreliable, because the algorithm would isolate the zeros of $b1,b2$ instead of the zeros of $b0=b1-b2$, so $b1,b2>0$ is not sufficient for concluding $b1-b2>0$. The second call is reliable as it correctly finds the roots of $b0$ in ($-3\pi,3\pi$). You can find the roots of MTPs in the information that our package prints, it goes as

- line 1: $k_-$, $k_+$ in Theorem 4.1 in our paper.
- line 2: Isolation intervals of all the roots of MTPs in $((2k_--1)\pi,(2k_++1)\pi)$, in the ascending order.
- line 3-n: The sign of MTPs at the roots, and the sign of MTPs between two adjacent roots.

So the users need to make sure that each atom in the first parameter is of the form $b_i?0$ and the second parameter lists all the $b_i$ in the first parameter, the third parameter specifies the MTP $f_i$ assigned to $b_i$.
3. As for the execution time, I have no clue but here is a guess: on my laptop, the second call costs 10.5625s and the third call (replacing x with x/2 then TrigExpand) costs 622.203s, however it is really fast to compute $k_-$ and $k_+$, the time-consuming part is isolating the real roots of MTPs in an interval. The isolation algorithm we used in the package is due to Strzebonski [[S08](https://dl.acm.org/doi/10.1145/1390768.1390810),[S09](https://dl.acm.org/doi/abs/10.1145/1576702.1576749),[S12](https://www.sciencedirect.com/science/article/pii/S0747717111001908)], which is built in Mathematica, it is fast on average but sometimes the performance is unstable. Also note that our implementation is different from the paper, which relies on a paper of McCallum and Weispfenning [[MW12](https://www.sciencedirect.com/science/article/pii/S0747717111001167)], to guarantee the unconditional theorectial completeness.

**Comment by xiaxueqaq** [comment] 2023-08-14 12:32
I believe the issue is resolved now. Closed due to inactiveness.

**Closed as completed by xiaxueqaq** 2023-08-14 12:32 UTC

**Comment by PoeticExposition** [comment] 2023-12-20 10:08
Apologies for my late reply. Is this project related to the previous [RootOfMTP](https://github.com/lihaokun/RootOfMTP?tab=readme-ov-file#rootofmtp)? 
Moreover, does there exist a blueprint for generalizing to certain bivariate MTPs (e.g., `ForAll[{x, y}, Element[x | y, PositiveReals] && x + y <= 2*Pi && x != y, Sin[x]/x + Sin[y]/y > 1 + (Sin[x] - Sin[y])/(x - y)]`)?

**Comment by xiaxueqaq** [comment] 2023-12-25 12:53
> Apologies for my late reply. Is this project related to the previous [RootOfMTP](https://github.com/lihaokun/RootOfMTP?tab=readme-ov-file#rootofmtp)? Moreover, does there exist a blueprint for generalizing to certain bivariate MTPs (e.g., `ForAll[{x, y}, Element[x | y, PositiveReals] && x + y <= 2*Pi && x != y, Sin[x]/x + Sin[y]/y > 1 + (Sin[x] - Sin[y])/(x - y)]`)?

1. The two projects are related in the way that they both apply the idea that sufficiently large real roots of an MTP share a similar pattern. But the goal is quite different, one is to "isolate" the real roots and the other is to verify a sentence in the FOL of MTP (I use quotation marks because it is not a real root isolation algorithm in the strict sense, since an interval may contain several roots). Also, techniques used in the proof are quite different and the arguments here are much more simplified.

2. Sorry, I do not know whether such a generalization exists, the best result I know is [[Theorem 3.1, M16](https://www.sciencedirect.com/science/article/pii/S0168007216300719)], which works for bounded variables, assuming Schanuel's Conjecture. But I get the vague impression that a complete algorithm (for unbounded variables) might not exist. 

Plus, our package is now available at [Wolfram Function Repository](https://resources.wolframcloud.com/FunctionRepository/resources/VerifyMTP). You are welcome to try the updated version, which does all the preprocessing for users now!

**Comment by PoeticExposition** [comment] 2023-12-28 06:10
Okay, I see. Many thanks!
